### ISSUE TITLE
Global section not being picked up (or imprecise docs)

### ISSUE THREAD

**Issue by krassowski** [jupyter/nbdime#521]
If I set my `nbdime_config.json` to:

```json
{
  "Global": {
    "Ignore": {
      "/cells/*/execution_count": false
    },
    "details": false
  }
}
```

I expect the `details` and `Ignore` to be applied to every nbdime tool, given that

> **Global** Options to apply to all commands.
[sections](https://github.com/jupyter/nbdime/blob/d44e3b5d09ba16163d71ef38e98f288c0a88b391/docs/source/config.rst#sections)

However, it is not applied to anything:

`nbdime --config` output fragment:

```
NbDiff:
  Ignore: {}
  attachments: <unset, resolves to true>
  color_words: false
  details: <unset, resolves to true>
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>
```

full output in details

<details>

```
All available config options, and their current values:

NbDiff:
  Ignore: {}
  attachments: <unset, resolves to true>
  color_words: false
  details: <unset, resolves to true>
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbDiffWeb:
  Ignore: {}
  attachments: <unset, resolves to true>
  base_url: "/"
  browser: null
  color_words: false
  details: <unset, resolves to true>
  ip: "127.0.0.1"
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  persist: false
  port: 0
  sources: <unset, resolves to true>
  workdirectory: "/home/krassowski/xx"

NbMerge:
  Ignore: {}
  attachments: <unset, resolves to true>
  color_words: false
  details: <unset, resolves to true>
  ignore_transients: true
  input_strategy: null
  merge_strategy: "inline"
  metadata: <unset, resolves to true>
  output_strategy: null
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbMergeWeb:
  Ignore: {}
  attachments: <unset, resolves to true>
  base_url: "/"
  browser: null
  color_words: false
  details: <unset, resolves to true>
  ignore_transients: true
  input_strategy: null
  ip: "127.0.0.1"
  merge_strategy: "inline"
  metadata: <unset, resolves to true>
  output_strategy: null
  outputs: <unset, resolves to true>
  persist: false
  port: 0
  sources: <unset, resolves to true>
  workdirectory: "/home/krassowski/xx"

NbShow:
  Ignore: {}
  attachments: <unset, resolves to true>
  details: <unset, resolves to true>
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

Server:
  base_url: "/"
  browser: null
  ip: "127.0.0.1"
  persist: false
  port: 8888
  workdirectory: "/home/krassowski/xx"

Extension:
  Ignore: {}
  attachments: <unset, resolves to true>
  color_words: false
  details: <unset, resolves to true>
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbDiffDriver:
  Ignore: {}
  attachments: <unset, resolves to true>
  color_words: false
  details: <unset, resolves to true>
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbDiffTool:
  Ignore: {}
  attachments: <unset, resolves to true>
  base_url: "/"
  browser: null
  color_words: false
  details: <unset, resolves to true>
  ip: "127.0.0.1"
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  persist: false
  port: 0
  sources: <unset, resolves to true>
  workdirectory: "/home/krassowski/xx"

NbMergeDriver:
  Ignore: {}
  attachments: <unset, resolves to true>
  color_words: false
  details: <unset, resolves to true>
  ignore_transients: true
  input_strategy: null
  merge_strategy: "inline"
  metadata: <unset, resolves to true>
  output_strategy: null
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbMergeTool:
  Ignore: {}
  attachments: <unset, resolves to true>
  base_url: "/"
  browser: null
  color_words: false
  details: <unset, resolves to true>
  ignore_transients: true
  input_strategy: null
  ip: "127.0.0.1"
  merge_strategy: "inline"
  metadata: <unset, resolves to true>
  output_strategy: null
  outputs: <unset, resolves to true>
  persist: false
  port: 0
  sources: <unset, resolves to true>
  workdirectory: "/home/krassowski/x"
```
</details>

Using `Diff` instead works:

```json
{
  "Diff": {
    "Ignore": {
      "/cells/*/execution_count": false
    },
    "details": false
  }
}
```

`nbdime --config` output fragment:

```
NbDiff:
  Ignore:
    /cells/*/execution_count: false
  attachments: <unset, resolves to true>
  color_words: false
  details: false
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>
```

full output in details

<details>
```
All available config options, and their current values:

NbDiff:
  Ignore:
    /cells/*/execution_count: false
  attachments: <unset, resolves to true>
  color_words: false
  details: false
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbDiffWeb:
  Ignore:
    /cells/*/execution_count: false
  attachments: <unset, resolves to true>
  base_url: "/"
  browser: null
  color_words: false
  details: false
  ip: "127.0.0.1"
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  persist: false
  port: 0
  sources: <unset, resolves to true>
  workdirectory: "/home/krassowski/xx"

NbMerge:
  Ignore: {}
  attachments: <unset, resolves to true>
  color_words: false
  details: <unset, resolves to true>
  ignore_transients: true
  input_strategy: null
  merge_strategy: "inline"
  metadata: <unset, resolves to true>
  output_strategy: null
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbMergeWeb:
  Ignore: {}
  attachments: <unset, resolves to true>
  base_url: "/"
  browser: null
  color_words: false
  details: <unset, resolves to true>
  ignore_transients: true
  input_strategy: null
  ip: "127.0.0.1"
  merge_strategy: "inline"
  metadata: <unset, resolves to true>
  output_strategy: null
  outputs: <unset, resolves to true>
  persist: false
  port: 0
  sources: <unset, resolves to true>
  workdirectory: "/home/krassowski/xx"

NbShow:
  Ignore: {}
  attachments: <unset, resolves to true>
  details: <unset, resolves to true>
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

Server:
  base_url: "/"
  browser: null
  ip: "127.0.0.1"
  persist: false
  port: 8888
  workdirectory: "/home/krassowski/xx"

Extension:
  Ignore:
    /cells/*/execution_count: false
  attachments: <unset, resolves to true>
  color_words: false
  details: false
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbDiffDriver:
  Ignore:
    /cells/*/execution_count: false
  attachments: <unset, resolves to true>
  color_words: false
  details: false
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbDiffTool:
  Ignore:
    /cells/*/execution_count: false
  attachments: <unset, resolves to true>
  base_url: "/"
  browser: null
  color_words: false
  details: false
  ip: "127.0.0.1"
  metadata: <unset, resolves to true>
  outputs: <unset, resolves to true>
  persist: false
  port: 0
  sources: <unset, resolves to true>
  workdirectory: "/home/krassowski/xx"

NbMergeDriver:
  Ignore: {}
  attachments: <unset, resolves to true>
  color_words: false
  details: <unset, resolves to true>
  ignore_transients: true
  input_strategy: null
  merge_strategy: "inline"
  metadata: <unset, resolves to true>
  output_strategy: null
  outputs: <unset, resolves to true>
  sources: <unset, resolves to true>

NbMergeTool:
  Ignore: {}
  attachments: <unset, resolves to true>
  base_url: "/"
  browser: null
  color_words: false
  details: <unset, resolves to true>
  ignore_transients: true
  input_strategy: null
  ip: "127.0.0.1"
  merge_strategy: "inline"
  metadata: <unset, resolves to true>
  output_strategy: null
  outputs: <unset, resolves to true>
  persist: false
  port: 0
  sources: <unset, resolves to true>
  workdirectory: "/home/krassowski/xx"

```
</details>
