### ISSUE TITLE
Make unchanged stderr output look more different from deleted outputs

### ISSUE THREAD

**Issue by cjerdonek** [jupyter/nbdime#747]
Currently, if an unchanged output item is from stderr (i.e. `"name": "stderr"` in the json), it looks very similar to deleted output. They are both reddish, though the unchanged stderr is more pink. See the following screenshot for an example:

<img width="670" alt="Screen Shot 2024-02-06 at 10 37 16 AM" src="https://github.com/jupyter/nbdime/assets/355822/0d7d17fb-5244-4ab4-8a92-26925fd79d35">

It would be better if they looked more different. For example, the stderr could be yellowish or something (for warning). The pink color comes from these parts of the html generated by nbdime:

```css
.jp-RenderedText[data-mime-type='application/vnd.jupyter.stderr'] {
  background: var(--jp-rendermime-error-background);
  padding-top: var(--jp-code-padding);
}
```
and
```css
/* Rendermime styles */

--jp-rendermime-error-background: #fdd; <-- PINK
--jp-rendermime-table-row-background: var(--md-grey-100);
--jp-rendermime-table-row-hover-background: var(--md-light-blue-50);
```
